### ISSUE TITLE
Quick Links are misaligned and quotes are not anchored to the bottom

### ISSUE THREAD

**Issue by yokai64** [joelshepherd/tabliss#452] opened 2022-03-11 17:27 UTC
Hi, noticed this this afternoon when I logged onto my PC and I assume there was an update recently

The text in the quick links i misaligned both with the default font and my custom one

As well as this the quote used to be at the bottom of the window but now it floats in the middle (if this is the new intended behaviour that's alright, i prefered it at the bottom but this is ok)

Here's a screenshot:
![image](https://user-images.githubusercontent.com/20884861/157916768-7fa45e44-958a-4475-a227-c5dc3b7dfda9.png)

(the quote is probably quite ironic in this situation 😝)

**Comment by joelshepherd** [comment] 2022-03-11 17:33
Yes, there was an update recently. No, that certainly is not intended behaviour!

I will be putting out a bugfix release in the next few days, I'll address these issues in there. Thanks!

**Comment by yokai64** [comment] 2022-03-11 17:54
> (Your new tab is very nice btw)

Ah thank you very much, keeps my head clear. Probably sounds strange but Tabless really improved my Chrome experience, it's so clean and it's completely ad free. Which reminds me, I'll send you a donation when I get paid because it's awesome that this project is free

**Comment by joelshepherd** [comment] 2022-03-13 17:08
Fixed in `2.3.0` going out today :tada:

**Closed by joelshepherd** 2022-03-13 17:08 UTC
