### ISSUE TITLE
Quotes don't change

### ISSUE THREAD

**Issue by SirBump** [joelshepherd/tabliss#423] opened 2021-12-05 04:18 UTC
I don't think this is intentional, but the quotes don't change unless I remove them and add them again.

**Comment by vintprox** [comment] 2021-12-19 20:28
Yeah, the quote is just saved once and doesn't change even on browser reload.

**Comment by joelshepherd** [comment] 2022-01-08 23:27
As in never change? Under the hood it uses a "quote of the day" API. Not that I remember anymore, but it might be it only updates once per day? Code-wise, Tabliss cache's the result for an hour.

**Comment by 0cwa** [comment] 2022-02-08 00:01
Is the quote the same as: [https://quotes.rest/qod.json](https://quotes.rest/qod.json)?
Maybe quotes.rest isn't changing?

**Comment by joelshepherd** [comment] 2022-03-10 14:49
I am unable to reproduce this. But from my testing, I have noticed the quotes API can be very slow at times (10 seconds to respond). If you kept closing your new tabs in less time that that, Tabliss would never get the opportunity to save the new quote, which may be the cause.

**Closed by joelshepherd** 2022-03-10 14:49 UTC

**Comment by lu-x** [comment] 2023-12-04 14:11
For me it's like:
- Daily Quotes don't work at all
- ~~Developer Excuses work one time (when i switch from "Daily Quotes"), then the quote never will change again~~ -> it changes after one day
