### ISSUE TITLE
Microsoft Edge Browser Mid night time error

### ISSUE THREAD

**Issue by BuddhikaD** [joelshepherd/tabliss#311] opened 2020-11-22 19:05 UTC
![image](https://user-images.githubusercontent.com/56988948/99914452-809fe580-2d23-11eb-877c-d5d419d21e51.png)

you can see this, in 24-hour clock system, its show in midnight like 24:00-24:59  its change at 01:00 am I'm looking at firefox its shows normally. please fix it

**Comment by BreakBB** [comment] 2020-11-26 08:06
Duplicate of #305

**Closed** 2020-12-01 14:15 UTC
