### ISSUE TITLE
24:32 ???

### ISSUE THREAD

**Issue by phamleduy04** [joelshepherd/tabliss#305] opened 2020-11-01 05:33 UTC
I think it should be 00:32, is there a setting for that?
![image](https://user-images.githubusercontent.com/32657584/97795895-c7ddff00-1bd9-11eb-8fb7-a8972e6822fe.png)

**Comment by BreakBB** [comment] 2020-11-26 08:08
Duplicate of #231

**Comment by joelshepherd** [comment] 2022-03-11 10:53
Duplicate of #362

**Closed by joelshepherd** 2022-03-11 10:53 UTC
