### ISSUE TITLE
Custom Font is inconsistent

### ISSUE THREAD

**Issue by ghost** [joelshepherd/tabliss#427] opened 2021-12-12 15:28 UTC
Hi,
I added a custom font to windows which wasn't recognized by Tabliss at first. After some time, it randomly worked but now, it does not work again. Do you know any fix?

Browser: Firefox Nightly

Best regards!

**Comment by neon-kite-creature** [comment] 2021-12-14 15:06
This may not be how any of this works, but this resourse helped me with configuring custom font options:
https://www.w3schools.com/Css/css_font.asp
I also used wordpad.exe's font auto-complete box to ensure that I had typed the font in correctly.

What operating system are you using? This and the way the font is installed may matter in this case. Is it provided by Google Fonts? If so, see here: https://tabliss.io/support.html

I hope I was of some help

**Comment by neon-kite-creature** [comment] 2021-12-14 15:21
Digging around, this appears to be the default string that whatever you type in the "Font" box in "Font options", it replaces:
`-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Roboto", "Helvetica Neue", Arial, sans-serif`

If you put `"[Font A]", [Font B]`, into the box, where Font A is the name of the font you want, and Font B is one of: `Monospace, Cursive, Fantasy`, what displays when it doesn't work.

This diagnostic step should help determine whether it is Tabliss, Firefox Nightly or your Operating System that is the root cause of the unexpected behaviour

**Comment by neon-kite-creature** [comment] 2021-12-14 15:27
Also when messing with options I found one should separate multiple fonts with a comma, but **_shouldn't_ end the custom font input with a comma**, i.e. **`Chiller, Comic Sans MS,`** or the ending comma will break the CSS

**Comment by joelshepherd** [comment] 2022-01-08 11:47
Custom fonts are powered by CSS and not Tabliss, so it's important to understand CSS to have fonts work correctly. Outside of that, I am not sure there is anything I can action for this ticket so I'll close it for now.

**Closed by joelshepherd** 2022-01-08 11:47 UTC
