### ISSUE TITLE
After restarting the computer all my widgets disappear

### ISSUE THREAD

**Issue by sinazadeh** [joelshepherd/tabliss#313] opened 2020-11-26 14:56 UTC
System:
Chrome version: Version 87.0.4280.66 (Official Build) (64-bit)
Windows 10 Education 64-bit
Tabliss Version 2.0.3

Problem:
Whenever I restart my computer, all my widgets and customizations will disappear.

**Comment by slushi66** [comment] 2020-12-06 13:21
same problem for me.
Everytime computer restart, tabliss reset to default all widgets. 
I though it was another extension but it's not, I tryed with all extensions disable.

System:
Chrome version: Version 87.0.4280.66 (Official Build) (64-bit)
Windows 10 HOME 64
Tabliss Version 2.0.3

**Comment by trmdi** [comment] 2020-12-11 16:38
Duplicate of https://github.com/joelshepherd/tabliss/issues/268

**Closed** 2021-03-16 00:14 UTC
