### ISSUE TITLE
Sync widgets/settings across browsers

### ISSUE THREAD

**Issue by chriskuech** [joelshepherd/tabliss#69] opened 2018-07-08 21:55 UTC
I would like widgets to sync with my Firefox account.  For example, editing todos and links in one browser should update in another browser.

I believe this is possible with the [storage.sync api](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync)

**Comment by joelshepherd** [comment] 2018-07-09 13:40
I have been wanting to implement syncing (along with multiple profiles, like home and work) for quite some time, and I have a serious look into the sync storage API.

But there has been 2 issues that have made the sync storage API unsuitable:
- The strict 100KB limit prevents me from storing every setting (most notably, the upload photo images)
- There is no conflict resolution logic, which can cause overriding/losing settings between browsers

I still do want to implement this feature however, and have looked into other options like AWS AppSync (or even just Cognito Sync). While the fees are pretty reasonable, the scale of Tabliss' user base plays against it there :(

So my options are really either integrate a "three-quarters of the way there" solution, or foot the fees and have a slick experience... yeah that's why I haven't implemented anything yet :joy:

**Comment by chriskuech** [comment] 2018-07-09 19:15
Looking at this a little more, I think you can literally find and replace `storage.local` with `storage.sync` (keeping `storage.local` for the images).  If you move image upload to a central blob store and only store references, you wont have to implement any external syncing APIs.  🤷‍♂️ 

Personally I would much rather have syncing support than image upload support 😛

**Comment by joelshepherd** [comment] 2018-07-17 10:23
The issue is everything is currently stored in IndexedDB, not `storage.local` or `storage.sync`.

The reason here is IndexedDB allows me to store images and assets in binary blob format instead of having to base64 encode them to local storage. This makes reading them from storage and displaying them on screen _much_ faster and uses less memory. This is what allows fresh Unsplash images to load so speedily! (or just your own personal upload ones :)

So it would be quite a big move that will involve splitting up my Redux store, and migrating everyone's settings, to make it happen.

I hope to revisit this issue in a month or so when my main job slows down a bit, and see if I can develop a nice solution :)

**Comment by linwaytin** [comment] 2018-12-04 00:58
I would suggest separating the text data from images. For me, the most important part is the todo list and the links. These are text data. I guess most people do not care sync background images so much.

If there is a method to read the todo/link from a text file, then the users can sync this file by themselves. Conflict may be handled by the method used to sync.

Anyway, this is a very nice project. Thanks a lot.

**Comment by chriskuech** [comment] 2018-12-06 23:40
@joelshepherd , if one were to reimplement text data storage in `storage.sync` (and it's a solid implementation) would you approve it?

**Comment by joelshepherd** [comment] 2018-12-07 10:11
I would! However there are some other issues with the storage mechanism that I would like to solve at the same time a storage refactor happens.

**1. Settings can be lost using the standard web storage areas (as opposed to extension storage)**
Running your browser in incognito or private mode causes Tabliss to loose access to its storage. This also applies to people who run their browsers in "always private mode" (Firefox), they loose their settings everytime the browser restarts.

The solution: The regular storage needs to be moved from IndexedDB to the browser's web extension storage APIs.

The caveat: The reason IndexedDB was originally chosen is because of its read speed, and it lets you store blobs (like images) in raw binary form, saving space and read time vs. base64 encoding it.

The other caveat: The storage API will requires the "storage" permission. I have tried my best to have Tabliss not require any permissions at all, and would preferably like to keep it that way if at all possible.

**2. Image blobs stored deep in the store are not encoded properly when the storage falls back to localStorage instead of IndexedDB**
This causes people who do not have IndexedDB enabled (or available), and have uploaded their own custom images to Tabliss, to have it crash when they restart.

Possible solutions:
1. Manually base64 encode images for storage (loosing the IndexedDB blob speed advantage)
2. Manually implement this idea for localForage: https://github.com/localForage/localForage/issues/380
3. Related to ^, move any stored images to a top-level storage key, but this would probably require a change to how plugins store data

I have been meaning to get to this for a while, but after I took a new job on earlier this year, I have not had much time to dedicate to the project 😢 

Happy to receive any feedback on these issues, in case anyone else has a better idea.

**Comment by chriskuech** [comment] 2018-12-07 22:13
Would it be easier to divide and conquer this by keeping the pics in IndexedDB and only moving the config data to storage?

**Comment by joelshepherd** [comment] 2018-12-10 06:38
Hm it could be. Move all image caches out of the Redux store and update the store to save to `storage.sync` instead? Then could tackle the image storing problems separately; possibly using method 3.

It would still require changing Tabliss' tagline from "(new tab blah blah)... that does not require any permissions." to "...that only requires one permission". Not quite the same ring!

**Comment by PyvesB** [comment] 2019-02-03 15:06
Maybe a first step could be to implement a manual import/export settings functionality?

**Comment by Excigma** [comment] 2019-07-14 06:28
Could you add an "Export Settings" to let you copy a JSON string?

**Comment by joelshepherd** [comment] 2019-07-17 02:19
Just a quick update on this one.

While I have been rewriting Tabliss (in branch `2`), I have successfully split out "text" and "blob" storage into separate stores that can be stored in different locations. This means I can now use the extension `sync` storage to sync your Tabliss settings between browsers! 🎉 

One question for anyone following along, do you sign in to your browsers to enable the browser's built in sync (I personally do not)? And is there a situation in which you would want to sync between between 2 different browsers (like Firefox and Chrome)?

I am asking to decide if I should develop some sort of "Tabliss acount" which you could sign into across different browsers, or if you are not signed into the browser's sync?

**Comment by PyvesB** [comment] 2019-07-17 06:25
I do tend to sign into Firefox, so the browser's built-in `sync` would probably work for me. However, there may be cases where users would want different layouts on different devices, how would Tabliss account for that? :wink:

**Comment by joelshepherd** [comment] 2019-07-17 08:35
My idea was to allow users to have multiple "profiles" that they can switch between, each profile saving a different layout. Then, in each browser you could choose which profile/layout to display.

I was not planning on doing that straight away. However you raise a good point, if I implement sync before profiles, it would break for any user who currently uses different layouts per browser.

**Comment by cwalker1960** [comment] 2019-12-16 14:19
I use different browsers, Chrome and Firefox and like some of the other users I don't care about the photos syncing just the links and todo list would be fine for me. As far as signing in to chrome and firefox thats about a 50/50 for me. If I need my bookmarks synced I do have to sign in but sometimes it'll be days or more between sign ins which wouldn't be very helpful for todo lists. Man it sure is tough trying to please everybody , LOL

**Comment by joelshepherd** [comment] 2020-04-14 06:09
This feature is now released in version 2!

There is still a limitation as I mentioned earlier in this thread, like it will not sync your custom uploaded photos. But we now sync on Firefox and Chrome when you are signed in.

**Closed by joelshepherd** 2020-04-14 06:09 UTC
Labels: enhancement

**Comment by OmriSama** [comment] 2020-04-14 22:18
> This feature is now released in version 2!
> 
> There is still a limitation as I mentioned earlier in this thread, like it will not sync your custom uploaded photos. But we now sync on Firefox and Chrome when you are signed in.

Sorry to reopen this, but do I have to turn syncing on anywhere? Didn't see any permissions requests from Tabliss... and my stuff doesn't seem to be syncing automatically.

**Comment by joelshepherd** [comment] 2020-04-14 23:18
No you do not need to turn it on. Tabliss 2 moves your settings to sync storage when you migrate your Tabliss 1 settings.

Are you signed into your browser? Sync only works if you login to sync with a Firefox or Chrome account.

**Comment by mxhsnowy** [comment] 2020-04-15 06:17
First of all, thank you for your beautiful extension, I am a new user and I'm very impressed with your work, the best new tab extension I've ever used.
I think the feature to import/export to a file is nice because with import/export users can export , for example their Chrome tabliss layout, links and to-dos to Firefox and Edge tabliss.

**Comment by codewing** [comment] 2020-04-16 10:47
I'm having the same issue as @OmriSama.

I've added some todos in my firefox on linux - pressed sync in my account and then switched to windows - pressed sync and they didn't sync.

**Comment by 1280px** [comment] 2020-10-15 23:48
Please add the ability to manually export the settings from extension, i.e. to transfer settings to another browser where I don't want to login, or to fast import/export in case of synced data corruption
