### ISSUE TITLE
On New tab, Search bar empties when Tabliss loads

### ISSUE THREAD

**Issue by MartinCura** [joelshepherd/tabliss#299] opened 2020-10-12 01:29 UTC
Hi there! Thanks for a simple yet wonderful extension. Been using it since forever but this issue seems to have cropped up kinda recently (it's been irking for at least some weeks but hadn't taken the minutes to explore the reasons).

(If you'd prefer i'd written to support@tabliss.io, sorry!)

As said, this is new "functionality", but really bothersome when you use the internets compulsively and search _a lot_ (and i do mean a lot). The issue is as follows:

**Whenever i open a new tab i can immediately start typing, but as soon as the Tabliss extension loads (meaning, "(Extension) Tabliss" appears in the left and the tabliss template starts showing up) whatever was already in the address bar is deleted.**

So in daily use i can try to quickly Ctrl+T and start typing a query, e.g. "how to ...", but mid sentence the first characters will be lost and if i press Enter i will duck an incomplete query. Of course, this isn't a showstopper, but it gets really tiring. I fear you won't be able to replicate it, because if that were the case someone else would've complained by now, no?

Interesting observation i just made trying this a couple dozen times: i think this is related to the mentioned "address bar prefix" loading kind of erratically. Every so often it doesn't load and thus my text is not lost.

I played around disabling extensions and effectively Tabliss seems to be the culprit (disabling makes the problem go away determinastically). I'm not 100 % sure it is, maybe if some other extension has a "prefix" as the one mentioned above i can replicate it with that.

Any ideas? Can try to screencap it if needed. Thanks!

**Comment by chezbgone** [comment] 2020-11-01 03:37
I have the exact same problem. I also think that the problem is related to the "address bar prefix" loading.

**Comment by TheLastGimbus** [comment] 2020-11-29 18:03
This is SO annoying - please fix it :cry:

**Comment by denniseffing** [comment] 2021-01-07 08:03
I have the same issue.

**Comment by graphixillusion** [comment] 2022-01-31 00:20
I'm still having the same issue: at start i very often need to insert the address/search queries two times becouse the first one is keeping resetting until tabliss is fully loaded. Very annoying indeed...

**Comment by joelshepherd** [comment] 2022-03-11 13:24
Can't say I have ever seen this issue, but it certainly sounds very annoying. Does it still do it in the latest (2.2.0) version?

**Comment by TheLastGimbus** [comment] 2022-03-11 17:12
I personally didn't have it for quite some time

**Comment by joelshepherd** [comment] 2022-03-19 06:50
That's good to hear! I think this may have been a browser bug that has since been resolved. I'll close this for now, but happy to reopen if the issue crops back up and looks like something Tabliss related.

**Closed by joelshepherd** 2022-03-19 06:50 UTC
